# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: niceb5y blog
email: niceb5y@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  몇번째 갈아엎는지 모를 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.niceb5y.net" # the base hostname & protocol for your site
twitter_username: niceb5y
github_username:  niceb5y
plugins: [jekyll-paginate, jekyll-sitemap]
paginate: 10
timezone: Asia/Seoul 
exclude: [src, webpack.config.js, package.json, node_modules]

# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
    style: compressed

highlighter: rouge
