baseURL = "https://blog.niceb5y.net/"
languageCode = "ko-kr"
title = "niceb5y blog"
theme = "n18"
copyright = "&copy; 2014-2018 niceb5y. / <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ko\">CC BY-NC-SA 4.0</a>"
hasCJKLanguage = true
defaultContentLanguage = "ko-kr"
pygmentsStyle = "monokai"
pygmentsCodefences = true
googleAnalytics = "UA-80539013-1"

[params]
  description = "몇번째 갈아엎는지 모를 블로그"
  author = "niceb5y"
