[build]
publish = "public"
command = "yarn run build"

[[redirects]]
from = "/feed.xml"
to = "/index.xml"
status = 301
force = false

[[redirects]]
from = "/page*"
to = "/page/:splat/"
status = 301
force = false

[[redirects]]
from = "/archive/"
to = "/"
status = 301
force = false

[[redirects]]
from = "/*"
to = "/404/index.html"
status = 404
force = false
