[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.55.6"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.55.6"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.55.6"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/feed.xml"
to = "/index.xml"
status = 301
force = false

[[redirects]]
from = "/page*"
to = "/page/:splat/"
status = 301
force = false

[[redirects]]
from = "/archive/"
to = "/"
status = 301
force = false

[[redirects]]
from = "/*"
to = "/404.html"
status = 404
force = false
